"""
modules/core/reporter.py

Generates a Markdown summary report (report.md) inside each domain's
output folder after all phases complete.
"""

import json
from pathlib import Path
from datetime import datetime


def _read_lines(path: Path) -> list[str]:
    if not path.exists():
        return []
    return [l for l in path.read_text(errors='replace').splitlines() if l.strip()]


def generate_report(domain: str, out_dir: Path) -> Path:
    out_dir     = Path(out_dir)
    report_file = out_dir / "report.md"
    now         = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

    # ── Collect stats ─────────────────────────────────────────────────────────
    subs     = _read_lines(out_dir / "subdomains.txt")
    alive    = _read_lines(out_dir / "alive.txt")
    ips      = _read_lines(out_dir / "ips.txt")
    paths    = _read_lines(out_dir / "traversal.txt")
    cnames   = _read_lines(out_dir / "cnames.txt")
    dns_recs = _read_lines(out_dir / "dns_records.txt")

    cdn_count = 0
    enrich_rows = []
    enrich_file = out_dir / "ip_enrichment.json"
    if enrich_file.exists():
        try:
            data = json.loads(enrich_file.read_text())
            for ip, d in sorted(data.items()):
                cdn = d.get('cdn') or ''
                cdn_count += 1 if cdn else 0
                cdn_tag   = f"  [CDN: {cdn}]" if cdn else ''
                enrich_rows.append(
                    f"{ip:<18} {d.get('country','?')}/{d.get('city','?')}  "
                    f"{d.get('as','')}{cdn_tag}"
                )
        except (json.JSONDecodeError, KeyError):
            pass

    # ── Build Markdown ────────────────────────────────────────────────────────
    def section(title: str) -> str:
        return f"\n## {title}\n"

    def code_block(lines: list[str], cap: int = 100, see_file: str = '') -> str:
        shown = lines[:cap]
        tail  = [f"… {len(lines)-cap} more — see {see_file}"] if len(lines) > cap and see_file else []
        return "```\n" + "\n".join(shown + tail) + "\n```\n"

    L = [
        f"# Recon Raptor — {domain}",
        f"",
        f"Generated: {now}",
        "",
        "## Summary",
        "",
        "| Metric                | Count |",
        "|-----------------------|-------|",
        f"| Subdomains discovered | {len(subs)} |",
        f"| Live hosts (HTTP/S)   | {len(alive)} |",
        f"| Unique IPs            | {len(ips)} |",
        f"| CDN-protected IPs     | {cdn_count} |",
        f"| CNAME records         | {len(cnames)} |",
        f"| DNS records (total)   | {len(dns_recs)} |",
        f"| Paths discovered      | {len(paths)} |",
        "",
    ]

    if subs:
        L += [section(f"Subdomains ({len(subs)})"),
              code_block(subs, 150, "subdomains.txt")]

    if alive:
        L += [section(f"Live Hosts ({len(alive)})"),
              code_block(alive, 80, "alive.txt")]

    if cnames:
        L += [
            section(f"CNAME Records ({len(cnames)})"),
            "> ⚠️  Review for potential subdomain takeover — dangling CNAMEs "
            "pointing to unclaimed cloud/SaaS services.",
            "",
            code_block(cnames, 200, "cnames.txt"),
        ]

    if enrich_rows:
        L += [section(f"IP Enrichment ({len(ips)} IPs, {cdn_count} CDN-protected)"),
              code_block(enrich_rows, 100, "ip_enrichment.json")]

    if paths:
        L += [section(f"Directory Traversal ({len(paths)} paths)"),
              code_block(paths, 200, "traversal.txt")]

    L += [
        "---",
        "_Generated by [Recon Raptor](https://github.com/yourorg/recon_raptor)_",
    ]

    report_file.write_text('\n'.join(L))
    print(f"    [+] report.md written ({len(subs)} subs · {len(alive)} alive · {len(paths)} paths)")
    return report_file
